"""
execution_prompt_router.py
-------------------------------
Test Execution prompt yönetimi için API endpoint'leri
"""

from fastapi import APIRouter, HTTPException, Body
from pydantic import BaseModel
from typing import Dict, Any
from core.prompt_manager import (
    get_base_prompt,
    save_custom_prompt
)

router = APIRouter(tags=["test_execution_prompts"])

class PromptSaveResponse(BaseModel):
    success: bool
    message: str

class TestExecutionPromptResponse(BaseModel):
    base_prompt: str
    system_suffix: str

@router.get("/api/prompts/test-execution", response_model=TestExecutionPromptResponse)
async def get_test_execution_prompt():
    """
    Test execution için prompt ve system_suffix döndürür.
    """
    try:
        base_prompt = get_base_prompt("test_execution")
        
        # Default test execution prompt if not found
        if not base_prompt:
            base_prompt = """You are an AI test execution agent operating within the STLC Manager project.

Your role is to execute test code and provide clear, accurate results exactly as they would appear in a terminal or execution environment.

Guidelines:
1. Execute the provided test code step by step
2. Return only raw execution output without additional explanations
3. Include any errors, warnings, or success messages as they would naturally occur
4. Maintain the exact format and structure of terminal output
5. Do not add commentary or interpretation unless explicitly requested

Test Execution Context:
- You are running tests generated by the STLC Manager test code generation process
- Tests may be in various programming languages (Python, JavaScript, Java, etc.)
- Provide execution results as if running in a real development environment
- Include relevant debugging information if tests fail"""

        system_suffix = """
Execute the test code and return the raw output exactly as it would appear in a terminal.
Do not add explanations, formatting, or commentary unless the code execution itself produces them.
"""
        
        return TestExecutionPromptResponse(
            base_prompt=base_prompt,
            system_suffix=system_suffix
        )
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/api/prompts/test-execution", response_model=PromptSaveResponse)
async def save_test_execution_prompt(data: Dict[str, Any] = Body(...)):
    """
    Test execution için yeni base prompt ekler.
    """
    try:
        new_prompt = data.get("base_prompt", "").strip()
        
        if not new_prompt:
            raise ValueError("Base prompt cannot be empty")
            
        result = save_custom_prompt("test_execution", new_prompt)
        
        if result:
            return PromptSaveResponse(
                success=True,
                message="Test execution prompt saved successfully"
            )
        else:
            return PromptSaveResponse(
                success=False,
                message="Failed to save test execution prompt"
            )
            
    except Exception as e:
        return PromptSaveResponse(
            success=False,
            message=f"Error saving prompt: {str(e)}"
        )